# Generated by Django 2.2.1 on 2019-07-02 13:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20190702_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='content',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.CharField(default=['starter'], max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.TextField(default='First Step'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=['main'], max_length=66, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
