version: '3'

services:
  django:
    build: ./backend/src
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend/src:/app/backend/src
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/gui
    command: ["npm", "start"]
    volumes:
      - ./frontend/gui:/app/frontend/gui
      - node-modules:/app/frontend/gui/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: